/* ==========================================================
   EIGAVERSA — Admin QR Scanner
   Scans an entry-pass QR code (generated by ticket.js) and
   auto-approves the matching registration.
   Uses jsQR (CDN) + getUserMedia, falls back to file input.
   ========================================================== */

(function () {
  'use strict';

  var modal = null;
  var video = null;
  var statusEl = null;
  var resultEl = null;
  var stream = null;
  var rafId = null;
  var awaiting = false;
  var cooldownUntil = 0;
  var resumeTimer = null;
  var lastScannedData = '';
  var lastScannedAt = 0;

  var canvas = document.createElement('canvas');
  var ctx = canvas.getContext('2d', { willReadFrequently: true });

  // firebase-service.js is a deferred module, so read the global lazily
  // at scan time instead of capturing it at script load.
  function getFirebase() {
    return window.EigaversaFirebase;
  }

  /* ---------- DOM helpers ---------- */

  function ensureModal() {
    if (modal) return modal;
    modal = document.createElement('div');
    modal.className = 'scan-modal';
    modal.setAttribute('role', 'dialog');
    modal.setAttribute('aria-modal', 'true');
    modal.setAttribute('aria-label', 'Scan entry pass');
    modal.innerHTML =
      '<div class="scan-modal-dialog">' +
        '<button type="button" id="scan-close-btn" class="scan-close" aria-label="Close scanner">&times;</button>' +
        '<div class="scan-modal-head">' +
          '<span class="scan-title">Scan Entry Pass</span>' +
          '<span class="scan-sub">Point the camera at the QR code on the pass</span>' +
        '</div>' +
        '<div class="scan-viewport">' +
          '<video id="scan-video" playsinline muted></video>' +
          '<div class="scan-frame" aria-hidden="true"></div>' +
        '</div>' +
        '<p id="scan-status" class="scan-status" role="status">Initializing camera...</p>' +
        '<div id="scan-result" class="scan-result" hidden></div>' +
        '<div class="scan-file-row">' +
          '<button type="button" id="scan-file-btn" class="btn btn-outline btn-sm">Upload QR image</button>' +
          '<input type="file" id="scan-file-input" accept="image/*" hidden>' +
        '</div>' +
      '</div>';
    document.body.appendChild(modal);
    video = document.getElementById('scan-video');
    statusEl = document.getElementById('scan-status');
    resultEl = document.getElementById('scan-result');

    document.getElementById('scan-close-btn').addEventListener('click', closeScanner);
    document.getElementById('scan-file-btn').addEventListener('click', function () {
      document.getElementById('scan-file-input').click();
    });
    document.getElementById('scan-file-input').addEventListener('change', onFilePicked);
    modal.addEventListener('click', function (e) {
      if (e.target === modal) closeScanner();
    });
    return modal;
  }

  function setStatus(msg, isError) {
    if (!statusEl) return;
    statusEl.textContent = msg;
    statusEl.classList.toggle('is-error', !!isError);
  }

  function showResult(html, isError) {
    if (!resultEl) return;
    resultEl.innerHTML = html;
    resultEl.hidden = false;
    resultEl.classList.toggle('is-error', !!isError);
  }

  function hideResult() {
    if (resultEl) {
      resultEl.hidden = true;
      resultEl.innerHTML = '';
    }
  }

  function escapeHtml(str) {
    return String(str == null ? '' : str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  /* ---------- Scanner control ---------- */

  function openScanner() {
    if (typeof window.jsQR !== 'function') {
      ensureModal();
      setStatus('Scanner library failed to load. Check your connection.', true);
      return;
    }
    if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
      ensureModal();
      setStatus('Camera not supported on this device. Use the upload option instead.', true);
      return;
    }

    ensureModal();
    modal.classList.add('is-active');
    document.body.style.overflow = 'hidden';
    hideResult();
    setStatus('Requesting camera access...');

    navigator.mediaDevices.getUserMedia({
      video: { facingMode: 'environment', width: { ideal: 1280 }, height: { ideal: 720 } },
      audio: false
    }).then(function (s) {
      stream = s;
      video.srcObject = s;
      video.setAttribute('playsinline', 'true');
      var playPromise = video.play();
      if (playPromise) {
        playPromise.catch(function () {
          setStatus('Camera could not start. Use the upload option instead.', true);
        });
      }
      setStatus('Scanning... Point the camera at the QR code.');
      awaiting = false;
      scanLoop();
    }).catch(function () {
      setStatus('Camera unavailable or permission denied. Use the upload option instead.', true);
    });
  }

  function scanLoop() {
    if (!video || video.readyState === 0) {
      rafId = requestAnimationFrame(scanLoop);
      return;
    }
    if (awaiting) {
      rafId = requestAnimationFrame(scanLoop);
      return;
    }
    if (Date.now() < cooldownUntil) {
      rafId = requestAnimationFrame(scanLoop);
      return;
    }
    if (video.videoWidth === 0) {
      rafId = requestAnimationFrame(scanLoop);
      return;
    }
    try {
      var sw = video.videoWidth;
      var sh = video.videoHeight;
      // Downscale for speed: jsQR runs much faster on a smaller image
      var scale = Math.min(1, 480 / Math.max(sw, sh));
      var w = Math.max(1, Math.round(sw * scale));
      var h = Math.max(1, Math.round(sh * scale));
      if (canvas.width !== w) {
        canvas.width = w;
        canvas.height = h;
      }
      ctx.drawImage(video, 0, 0, w, h);
      var imageData = ctx.getImageData(0, 0, w, h);
      var code = window.jsQR(imageData.data, w, h, { inversionAttempts: 'attemptBoth' });
      if (code && code.data) {
        // Ignore the same payload repeated in the frame
        if (code.data === lastScannedData && Date.now() - lastScannedAt < 2500) {
          rafId = requestAnimationFrame(scanLoop);
          return;
        }
        handleScan(code.data);
        // scanLoop intentionally not chained here; handleScan resumes it.
      } else {
        rafId = requestAnimationFrame(scanLoop);
      }
    } catch (e) {
      rafId = requestAnimationFrame(scanLoop);
    }
  }

  function resumeScan(delayMs) {
    awaiting = false;
    stopScanLoop();
    clearTimeout(resumeTimer);
    resumeTimer = setTimeout(function () {
      if (stream) scanLoop();
    }, delayMs || 0);
  }

  function stopScanLoop() {
    if (rafId) {
      cancelAnimationFrame(rafId);
      rafId = null;
    }
  }

  function closeScanner() {
    stopScanLoop();
    clearTimeout(resumeTimer);
    if (stream) {
      stream.getTracks().forEach(function (t) { t.stop(); });
      stream = null;
    }
    if (video) video.srcObject = null;
    if (modal) modal.classList.remove('is-active');
    document.body.style.overflow = '';
    awaiting = false;
    lastScannedData = '';
  }

  /* ---------- File upload scanning ---------- */

  function onFilePicked(e) {
    var file = e.target.files && e.target.files[0];
    if (!file) return;
    var url = URL.createObjectURL(file);
    var img = new Image();
    img.onload = function () {
      try {
        var iw = img.naturalWidth || 600;
        var ih = img.naturalHeight || 600;
        canvas.width = iw;
        canvas.height = ih;
        ctx.drawImage(img, 0, 0);
        var imageData = ctx.getImageData(0, 0, iw, ih);
        var code = window.jsQR(imageData.data, iw, ih, { inversionAttempts: 'attemptBoth' });
        URL.revokeObjectURL(url);
        if (code && code.data) {
          handleScan(code.data);
        } else {
          setStatus('No QR code found in that image.', true);
        }
      } catch (err) {
        URL.revokeObjectURL(url);
        setStatus('Could not read that image.', true);
      }
    };
    img.onerror = function () {
      URL.revokeObjectURL(url);
      setStatus('Could not read that image.', true);
    };
    img.src = url;
    e.target.value = '';
  }

  /* ---------- Payload handling ---------- */

  // Payload: EIGAVERSA|<regId>|<SOLO|GROUP>|<name>|<docId>
  function parsePayload(text) {
    if (!text) return null;
    var s = String(text).trim();
    if (s.indexOf('EIGAVERSA|') !== 0) return null;
    var parts = s.split('|');
    return {
      regId: (parts[1] || '').trim().toUpperCase(),
      type: (parts[2] || '').toUpperCase(),
      name: parts[3] ? parts[3].trim() : '',
      docId: parts[4] ? parts[4].trim() : ''
    };
  }

  function resultHTML(kind, regId, displayName, typeLabel) {
    var strong = kind === 'already' ? 'Already Approved' : 'Registration Approved';
    return '<span class="scan-result-icon">&#10003;</span>' +
      '<strong>' + strong + '</strong>' +
      '<span class="scan-result-id">' + escapeHtml(regId) + '</span>' +
      '<span class="scan-result-name">' + escapeHtml(displayName) + ' <em>(' + typeLabel + ')</em></span>';
  }

  function approveDirect(payload) {
    var collName = payload.type === 'GROUP' ? 'eigaversa_groups' : 'eigaversa_solo';
    var typeLabel = payload.type === 'GROUP' ? 'Group' : 'Solo';
    var fb = getFirebase();
    fb.updateRegistrationStatus(collName, payload.docId, 'approved').then(function (ok) {
      if (ok) {
        showResult(resultHTML('approved', payload.regId, payload.name || 'Participant', typeLabel));
      } else {
        setStatus('Failed to approve ' + payload.regId + '. Try again.', true);
      }
      cooldownUntil = Date.now() + 2000;
      resumeScan(2600);
    });
  }

  function approveAfterLookup(payload) {
    var regId = payload.regId;
    var fb = getFirebase();
    fb.getRegistrationById(regId).then(function (record) {
      if (!record) {
        setStatus('No registration found for ' + regId + '.', true);
        cooldownUntil = Date.now() + 1500;
        resumeScan(1800);
        return;
      }

      var collName = (record.type === 'group' || record.teamName)
        ? 'eigaversa_groups'
        : 'eigaversa_solo';

      var displayName = record.teamName || record.name || 'Participant';
      var typeLabel = (record.type === 'group' || record.teamName) ? 'Group' : 'Solo';

      if (record.status === 'approved') {
        showResult(resultHTML('already', record.registrationId || regId, displayName, typeLabel));
        cooldownUntil = Date.now() + 2000;
        resumeScan(2600);
        return;
      }

      fb.updateRegistrationStatus(collName, record.id, 'approved').then(function (ok) {
        if (ok) {
          showResult(resultHTML('approved', record.registrationId || regId, displayName, typeLabel));
          cooldownUntil = Date.now() + 2000;
          resumeScan(2600);
        } else {
          setStatus('Failed to approve ' + regId + '. Try again.', true);
          cooldownUntil = Date.now() + 1500;
          resumeScan(1800);
        }
      });
    }).catch(function () {
      setStatus('Lookup failed. Check your connection.', true);
      cooldownUntil = Date.now() + 1500;
      resumeScan(1800);
    });
  }

  function handleScan(text) {
    if (awaiting) return;
    var payload = parsePayload(text);
    if (!payload || !payload.regId) return;

    var fb = getFirebase();
    if (!fb || !fb.isConfigured()) {
      setStatus('Firebase is not configured.', true);
      return;
    }

    awaiting = true;
    lastScannedData = text;
    lastScannedAt = Date.now();

    // Fast path: docId is baked into the QR -> single Firestore write.
    // No lookup query, so approval happens in milliseconds.
    if (payload.docId) {
      setStatus('Approving ' + payload.regId + ' ...');
      approveDirect(payload);
      return;
    }

    // Fallback for passes encoded without a docId.
    setStatus('Checking ' + payload.regId + ' ...');
    approveAfterLookup(payload);
  }

  /* ---------- Wiring ---------- */

  document.addEventListener('DOMContentLoaded', function () {
    var openBtn = document.getElementById('scan-qr-btn');
    if (!openBtn) return;
    openBtn.addEventListener('click', openScanner);
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') closeScanner();
    });
  });
})();
